container:
  image: ubuntu:18.04

env:
  VERSION: 1.0
  GITHUB_TOKEN: ENCRYPTED[7c3d72bc0ee5534edcf0918778788f24b5dd0bc06d7dc0bdf767091020b1a5ab7734ded6174551dc6c27b1f76505a092]

task:
  only_if: $CIRRUS_BRANCH == "master"

  timeout_in: 90m

  install_apt_script: |
    apt-get update
    apt-get -y install wget curl make gcc file g++ patch cpio python unzip rsync bc libdata-dumper-simple-perl libextutils-makemaker-cpanfile-perl libthread-queue-any-perl jq zip

  ccache_cache:
    folder: /tmp/buildroot-ccache

  build_script: ./build.sh

  publish_script: ./publish.sh "./build/output/images/sdcard.img" $VERSION
